services:
  - type: web
    name: controle-dp-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: dpsmart2026chaveSecretaForte
      - key: DATABASE_URL
        value: postgresql://controle_dp_user:cyetQPAPdYMqgJkpQP3rXJCHbtTdMAVZ@dpg-d7ogra9f9bms73dmvlcg-a/controle_dp

  - type: static
    name: controle-dp-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: dpsmart-db
    databaseName: dpsmart
    user: dpsmart
    plan: free
